apiVersion: v1
kind: ConfigMap
metadata:
  name: web-configmap
  labels:
    app: simple-app
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Simple app punya nita baru.</h1>
    </html>
